config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root 'games#index'

  post 'sessions/create'
  delete 'sessions/destroy'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :games, only: [:index, :show]
  resources :moves, only: [:create]

  get 'pieces/:id/deselect', to: 'pieces#deselect'

  post 'games/refresh', to: 'games#refresh', as: 'refresh_game'
  get 'games/:id/choose-party', to: 'games#choose_party', as: 'choose_party'
  post 'games/:id/join', to: 'games#join', as: 'join_game'

  if Rails.env.development?
    mount Sidekiq::Web => "/sidekiq"

    get 'games/:id/process_moves', to: 'games#process_moves', as: 'process_moves'
    get 'games/:id/stop_processing_moves', to: 'games#stop_processing_moves', as: 'stop_processing_moves'
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players

  def current_color
    if self.current_turn.even? then WHITE else BLACK end
  end

  def current_points
    points = {
      WHITE => 0,
      BLACK => 0,
    }

    Game.includes(players: :pieces).find(self.id).players.map do |player|
      points[player.color] += player.get_points.values.sum
    end

    points
  end

  def create_player!
    points = self.current_points

    is_black = if points[WHITE] > points[BLACK]
      true
    elsif points[BLACK] > points[WHITE]
      false
    else
      [true, false].sample
    end

    self.players.create!(is_black: is_black, points: Player::STARTING_POINTS)
  end

  def first_square(board_x, board_y)
    self.location_to_square({ board_x: board_x, board_y: board_y, x: 0, y: 0 })
  end

  def empty_squares(board_x, board_y, pieces: nil)
    pieces ||= self.pieces_by_board[[board_x, board_y]]
    first_square = self.first_square(board_x, board_y)
    (first_square...first_square + 64).to_a - pieces.map(&:square)
  end

  def choose_starting_board(player:, count:)
    coords = []
    self.boards_tall.times do |board_y|
      self.boards_wide.times do |board_x|
        coords << [board_x, board_y]
      end
    end

    coords.shuffle.each do |board_x, board_y|
      pieces = self.pieces_by_board[[board_x, board_y]]
      if pieces.all? { |piece| piece.player.color == player.color }
        empty_squares = self.empty_squares(board_x, board_y, pieces: pieces)

        if empty_squares.length > count
          return [board_x, board_y]
        end
      end
    end

    return nil
  end

  if Rails.env.development?
    def reset
      Game.includes(players: { pieces: :moves })
        .find_by(id: self.id)
        .players
        .flat_map(&:pieces)
        .flat_map(&:moves)
        .map(&:destroy!)

      self.update!(current_turn: 0)
    end
  end

  def board_hash(value_type)
    h = {}

    self.boards_tall.times do |board_y|
      self.boards_wide.times do |board_x|
        h[[board_x, board_y]] = {
          array: [],
          hash: {},
        }[value_type] || raise("game.board_hash: unknown value_type #{value_type}")
      end
    end

    h
  end

  def pieces_by_board
    @pieces_by_board ||= begin
      h = self.board_hash(:array)

      players.includes(:pieces).each do |player|
        player.pieces.each do |piece|
          location = self.square_to_location(piece.square)
          h[[location[:board_x], location[:board_y]]] << piece
        end
      end

      h
    end
  end

  # Each board is 64 consecutive indexes:
  # + - - - - - - - - + - - - - - - - - +
  # | 0 1 2 3 4 5 6 7 | 64 64 66 ...    |
  # | 8 9 ...         |                 |
  # |                 |                 |
  # |                 |                 |
  # |                 |                 |
  # |                 |                 |
  # |                 |                 |
  # |    ... 61 62 63 |     ... 126 127 |
  # + - - - - - - - - + - - - - - - - - +
  # | 128 129 ...     |                 |
  # |                 |                 |
  # |                 |                 |
  # |                 |                 |
  # |                 |                 |
  # |                 |                 |
  # |                 |                 |
  # |                 |                 |
  # + - - - - - - - - + - - - - - - - - +
  def location_to_square(location)
    squares_per_board_row = self.boards_wide * 64

    (location[:board_y] * squares_per_board_row) +
      (location[:board_x] * 64) +
      (location[:y] * 8) +
      location[:x]
  end

  def square_to_location(square)
    squares_per_board_row = self.boards_wide * 64

    board_y = square / squares_per_board_row
    square %= squares_per_board_row

    board_x = square / 64
    square %= 64

    y = square / 8
    square %= 8

    x = square

    {
      board_x: board_x,
      board_y: board_y,
      x: x,
      y: y,
    }
  end

  def build_cache
    cache = {}

    all_pieces = Game.includes(players: { pieces: :moves }).find(self.id).players.flat_map(&:pieces)
    all_pieces.each do |piece|
      move = piece.current_move(self)
      intermediate_squares = if move
        move.get_intermediate_squares
      else
        [piece.square] * Move::INTERMEDIATE_SQUARES_PER_TURN
      end

      cache[piece.id] = {
        piece: piece,
        move: move,
        intermediate_squares: intermediate_squares,
      }
    end

    cache
  end

  def get_move_steps(cache)
    steps = {}

    bumped_pieces = Set.new
    captured_pieces = Set.new

    board_hash = self.board_hash(:array)

    Move::INTERMEDIATE_SQUARES_PER_TURN.times.map do |idx|
      board_hash.each.with_index do |((board_x, board_y), _), board_idx|
        steps[[board_x, board_y]] ||= []
        step = {}

        get_stage = -> (piece) do
          stage = Piece::Stage.new
          intermediate_squares = cache[piece.id][:intermediate_squares]
          current_square = intermediate_squares[idx]
          previous_square = idx > 0 && intermediate_squares[idx - 1]
          stage.target_square = current_square
          previous_square = if idx == 0
            piece.square
          else
            cache[piece.id][:intermediate_squares][idx - 1]
          end

          previous_location = self.square_to_location(previous_square)
          stage.original_board = [previous_location[:board_x], previous_location[:board_y]]

          if captured_pieces.include?(piece.id)
            stage.kind = :captured
          else
            if piece.square == current_square
              stage.kind = :initial
            elsif idx > 0 && current_square == previous_square
              stage.kind = :moved
            else
              stage.is_array = true
              stage.kind = :moving
            end
          end

          stage
        end

        cache.each do |_piece_id, piece_cache|
          piece = piece_cache[:piece]
          current_square = piece_cache[:intermediate_squares][idx]
          current_location = self.square_to_location(current_square)

          if current_location[:board_x] == board_x && current_location[:board_y] == board_y
            piece_stage = if bumped_pieces.include?(piece.id)
              original_piece_location = self.square_to_location(piece.square)
              original_board_x, original_board_y = [original_piece_location[:board_x], original_piece_location[:board_y]]
              steps[[original_board_x, original_board_y]][idx] ||= {}
              steps[[original_board_x, original_board_y]][idx].merge!(piece.square => { bumped: piece.id })

              Piece::Stage.new(kind: :bumped, target_square: piece.square, original_board: [original_board_x, original_board_y])
            else
              get_stage.(piece)
            end
            step[piece_stage.target_square] ||= {}

            def changed_boards(stage)
              target_location = self.square_to_location(stage.target_square)
              original_board_x, original_board_y = [stage.original_board[0], stage.original_board[1]]

              original_board_x != target_location[:board_x] || stage.original_board[1] != target_location[:board_y]
            end

            if changed_boards(piece_stage)
              original_piece_location = self.square_to_location(piece.square)
              original_board_x, original_board_y = [original_piece_location[:board_x], original_piece_location[:board_y]]

              steps[[original_board_x, original_board_y]] ||= []
              steps[[original_board_x, original_board_y]][idx] ||= {}

              # `piece_stage.is_array` will always be true if changed_boards is true because the only way to change
              # boards is to be :moving (since :bumped is handled separately).
              steps[[original_board_x, original_board_y]][idx][piece_stage.target_square] ||= {}
              steps[[original_board_x, original_board_y]][idx][piece_stage.target_square][piece_stage.kind] ||= []
              steps[[original_board_x, original_board_y]][idx][piece_stage.target_square][piece_stage.kind] << piece.id
            end

            if piece_stage.is_array
              step[piece_stage.target_square][piece_stage.kind] ||= []
              step[piece_stage.target_square][piece_stage.kind] << piece.id
            else
              step[piece_stage.target_square][piece_stage.kind] = piece.id
            end

            step.each do |square, piece_steps|
              bump_moving_pieces = if piece_steps[:moving]
                if piece_steps[:moving].length > 1
                  # Many pieces arrived at the square at the same time.
                  true
                elsif piece_steps[:moving].length == 1
                  if piece_steps[:moved]
                    # Another piece already arrived at this square first.
                    true
                  elsif piece_steps[:initial]
                    moving_piece = cache[piece_steps[:moving].only!][:piece]
                    other_piece = cache[piece_steps[:initial]][:piece]

                    if other_piece.player.is_black == moving_piece.player.is_black
                      # Another piece was here and didn't move this turn.
                      true
                    else
                      if !captured_pieces.include?(other_piece.id)
                        # TODO Move this into apply_move_steps so all db updates happen there.
                        moving_piece.player.update!(
                          points: moving_piece.player.points + other_piece.points,
                        )
                        captured_pieces.add(other_piece.id)
                      end

                      false
                    end
                  end
                end
              end

              chain_bump = -> (piece_id) do
                chained_bump_square = cache[piece_id][:piece].square

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_current_player, except: [:index]
  before_action :require_choosing_party_status, only: [:choose_party, :join]

  def index
    if @player = current_player
      path = if @player.status == CHOOSING_PARTY
        choose_party_path(@player.game.id)
      else
        game_path(@player.game.id)
      end

      redirect_to(path)
    end

    @games = Game.all
  end

  def show
    @player = current_player

    if @player.game.id != params[:id].to_i
      redirect_to(game_path(@player.game.id))
    elsif @player.status == CHOOSING_PARTY
      redirect_to choose_party_path(@player.game.id)
    end
  end

  def choose_party
    @player = current_player
  end

  def join
    @player = current_player

    kinds = params[:chosen_kinds].split(',')
    starting_board_x, starting_board_y =
      @player.game.choose_starting_board(player: @player, count: kinds.length)

    begin
      @player.create_starting_pieces!(
        kinds: kinds,
        starting_board_x: starting_board_x,
        starting_board_y: starting_board_y,
      )
    rescue => e
      flash[:error] = "Something went wrong - please try again."
      return redirect_to(choose_party_path(@player.game.id))
    end

    @player.update!(status: JOINING)

    redirect_to(game_path(@player.game.id))
  end

  # TODO Maybe don't call this "refresh" since it doesn't refresh the browser page.
  def refresh
    game = Game.find(params[:game_id])
    player = game.players.find(params[:player_id])

    game.broadcast_refresh(player)

    head :ok
  end

  if Rails.env.development?
    def process_moves
      game = Game.find(params[:id])
      ProcessMovesJob.perform_later(game.id, game.current_turn)

      head :ok
    end

    def stop_processing_moves
      game = Game.find(params[:id])
      game.update!(stop_processing_moves_at: game.current_turn + 1)

      head :ok
    end
  end

  private

  def require_current_player
    if current_player.nil?
      redirect_to :root
    end
  end

  def require_choosing_party_status
    if current_player.status != CHOOSING_PARTY
      redirect_to game_path(current_player.game.id)
    end
  end
end

app/views/games/_board_grid.html.erb
<%
selected_piece ||= nil
currently_moving = player.game.current_color
# Using an empty string because js checks this value, so it has to evaluate to `false`.
moves_allowed = if player.color == currently_moving then 'yes' else '' end
pending_moves = player.pending_moves_by_board
%>

<div id='board-grid'
     class='board-grid'
     data-environment='<%= Rails.env %>'
     data-boards-tall='<%= player.game.boards_tall %>'
     data-boards-wide='<%= player.game.boards_wide %>'
     data-moves-allowed-now='<%= moves_allowed %>'
>
  <%= turbo_stream.replace("header", render(partial: "games/board_header", locals: { player: player })) %>

  <% player.game.boards_tall.times do |board_y| %>
    <div class='board-row'>
      <% player.game.boards_wide.times do |board_x| %>
        <%
        pieces_on_board = player.game.pieces_by_board[[board_x, board_y]]
        has_piece_on_board = pieces_on_board.any? { |piece| piece.player.id == player&.id }
        %>

        <div id="board-<%= "#{board_x}-#{board_y}" %>" class="board">
          <% 8.times do |y| %>
            <% 8.times do |x| %>
              <% span_class = "#{y%2 == x%2 ? 'light' : 'dark'}-#{has_piece_on_board ? 'revealed' : 'obscured'}" %>
              <span class="square <%= span_class %>">
                <% if Rails.env.development? %>
                  <%= player.game.location_to_square({board_x: board_x, board_y: board_y, x: x, y: y}) %>
                <% end %>
              </span>
            <% end %>
          <% end %>
          <% if has_piece_on_board %>
            <% pieces_on_board.each do |piece| %>
              <% location = player.game.square_to_location(piece.square) %>
              <%= render partial: piece, locals: {
                player: player,
                selected_piece: selected_piece,
                board_x: board_x,
                board_y: board_y,
                x: location[:x],
                y: location[:y],
              } %>
            <% end %>
          <% end %>

          <% pending_moves[[board_x, board_y]].each do |move| %>
            <div class="pending-move"
                 data-piece-id="<%= move.piece_id %>"
                 style="<%= get_pending_move_line(player.game, move, board_x, board_y) %>"
            ></div>
          <% end %>
        </div>
      <% end %>
      <br />
    </div>
  <% end %>
</div>

app/views/games/_board_header.html.erb
<%
seconds_elapsed = Time.now.utc - player.game.last_turn_completed_at
yellow_light_duration = 5 # TODO maybe vary this based on min_turn_duration
green_seconds_remaining = (player.game.minimum_turn_duration - yellow_light_duration) - seconds_elapsed
green_light_timeout = green_seconds_remaining * 1000
%>

<div id="header">
  <% if player.status == DEAD %>
    <%= render partial: "games/game_over", locals: { player: player } %>
  <% else %>
    <div id="turn-indicator"
         data-controller="turn-indicator"
         data-turn-indicator-current-color-value="<%= player.game.current_color %>"
         data-turn-indicator-green-light-timeout-value="<%= green_light_timeout %>"
         data-action="refresh:setRedLight@window->turn-indicator#setRedLight"
    >
      <div id="traffic-lights">
        <div id="green-light" class="traffic-light"></div>
        <div id="yellow-light" class="traffic-light"></div>
        <div id="red-light" class="traffic-light"></div>
      </div>
    </div>
    <div id="spawn-pieces"
         data-controller="spawn-piece"
    >
      <% points = player.get_points %>
      <% Piece::KINDS.each do |kind| %>
        <% affordable = points[:bank] >= Piece.cost(kind) %>
        <div class="spawn-piece-button-container <%= if affordable then 'affordable' else 'not-affordable' end %>">
          <%= image_tag("#{player.color}-#{kind}",
                        class: "piece-button",
                        data: {
                          kind: kind,
                          spawn_piece_target: "button",
                          action: "click->spawn-piece#selectPiece",
                          affordable: if affordable then 'yes' else '' end,
          })
          %>
          <div class="piece-cost"><%= Piece.cost(kind) %></div>
        </div>
      <% end %>

      <div id="points">
        <div>Bank: <%= points[:bank] %></div>
        <div>Pending: <%= points[:pending] %></div>
        <div>On board: <%= points[:on_board] %></div>
        <div style='border-top: 1px solid black'>Total: <%= points.values.sum %></div>
      </div>
    </div>
    <div id="score">Score: <%= player.score %></div>
    <div id="quit-button">
      <%= button_to("Quit game", sessions_destroy_path, { method: :delete }) %>
    </div>
  <% end %>
</div>

app/views/games/_game_over.html.erb
<div id="game-over">
  <div>
    Game Over
  </div>

  <div id="game-over-stats">
    <div>Final Score: <%= player.score %></div>
  </div>

  <div id="quit-button">
    <%= button_to("Quit game", sessions_destroy_path, { method: :delete }) %>
  </div>
</div>

app/views/games/_moves.html.erb
<% step_time = 300 %>

<div id="game-moves">
  <% if move_steps %>
    <% move_steps.each do |(board_x, board_y), steps| %>
      <% steps.each.with_index do |step, idx| %>
        <div data-controller="move"
             data-move-current-color-value="<%= player.game.current_color %>"
             data-move-enemy-color-value="<%= if player.color == WHITE then BLACK else WHITE end %>"
             data-move-wait-time-value="<%= idx * step_time %>"
             data-move-step-value="<%= step.to_json %>"
             data-move-moves-from-hidden-boards-value="<%= moves_from_hidden_boards&.to_json || '[]' %>"
        >
        </div>
      <% end %>
    <% end %>

    <div id="refresh-grid"
         data-controller="refresh"
         data-refresh-wait-time-value="<%= step_time * Move::INTERMEDIATE_SQUARES_PER_TURN %>"
         data-refresh-game-id-value="<%= player.game.id %>"
         data-refresh-player-id-value="<%= player.id %>"
    >
    </div>
  <% end %>
</div>

app/views/games/choose_party.html.erb
<!-- CLEANUP this is currently the only page that can have flash messages, but this should probably be on the layout -->
<div id="flash-notification">
  <% if flash[:error] %>
    <div class="flash-error">
      <%= flash[:error] %>
    </div>
  <% end %>
</div>

<%= render partial: "pieces/images" %>

<% points = @player.get_points[:bank] %>
<div id="choose-party"
     data-controller="choose-party"
     data-choose-party-bank-value=<%= points %>
     data-choose-party-color-value=<%= @player.color %>
>
  <div>
    Choose your party!
  </div>
  <div id="choose-party-buttons">
    <% Piece::KINDS.each do |kind| %>
      <div class="choose-party-button-container">
        <%= image_tag("#{@player.color}-#{kind}",
                      class: "piece-button",
                      data: {
                        kind: kind,
                        cost: Piece.cost(kind),
                        choose_party_target: 'button',
                        action: "click->choose-party#choosePiece",
                        affordable: 'yes',
        })
        %>
        <div class="piece-cost"><%= Piece.cost(kind) %></div>
      </div>
    <% end %>
  </div>

  <div>
    Points remaining: <span data-choose-party-target="bank"><%= points %></span>
  </div>
  <div id="current-party-container">
    Current party:

    <div id="current-party"></div>
  </div>

  <%= button_to({ action: "join" }, { id: 'join-button', disabled: true }) do %>
    Join
    <%= hidden_field_tag :chosen_kinds, "", id: "js-chosen-kinds" %>
  <% end %>
</div>

app/views/games/index.html.erb
<div>Games</div>

<%
all_dimensions = @games.map { |game| [game.boards_wide, game.boards_tall] }.uniq
all_durations = @games.map { |game| game.minimum_turn_duration }.uniq
%>

<table>
  <thead>
    <tr>
      <th scope="col"></th>
      <% all_durations.each do |duration| %>
        <th scope="col"><%= duration %> seconds</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% all_dimensions.each do |dimensions| %>
      <tr>
        <th scope="row"><%= dimensions[0] %> x <%= dimensions[1] %></th>
        <% all_durations.each do |duration| %>
          <% if game = @games.find_by(boards_wide: dimensions[0], boards_tall: dimensions[1], minimum_turn_duration: duration) %>
            <td>
              <div><%= game.players.count %> Players</div>
              <div class='join-button'><%= button_to("Join", sessions_create_path, { params: { game_id: game.id } }) %></div>
            </td>
          <% else %>
            <td></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/join.html.erb
<div id="choose-party"
     data-controller="choose-party"
     data-choose-party-bank-value=<%= @player.get_points[:bank] %>
>
  <div>
    Choose your party!
  </div>
  <div id="choose-party-buttons">
    <% Piece::KINDS.each do |kind| %>
      <div class="choose-party-button-container">
        <%= image_tag("#{@player.color}-#{kind}",
                      class: "piece-button",
                      data: {
                        kind: kind,
                        cost: Piece.cost(kind),
                        choose_party_target: 'button',
                        action: "click->choose-party#choosePiece",
                        affordable: 'yes',
        })
        %>
        <div class="piece-cost"><%= Piece.cost(kind) %></div>
      </div>
    <% end %>
  </div>

  <div>
    Points remaining: <span data-choose-party-target="bank">...</span>
  </div>
  <div id="current-party-container">
    Current party:

    <div id="current-party"></div>
  </div>
</div>

app/views/games/show.html.erb
<%= link_to("back", games_path) %>

<div id="content-container">
  <% if Rails.env.development? %>
    <h1>Game <%= @player.game.id %></h1>

    <h4>Playing as <%= @player.id %></h4>

    <div>
      <%= button_to("process moves", process_moves_path(id: @player.game.id), { method: :get }) %>
    </div>
    <div>
      <%= button_to("stop processing moves", stop_processing_moves_path(id: @player.game.id), { method: :get }) %>
    </div>
  <% end %>

  <%= render partial: "pieces/images" %>

  <%= turbo_stream_from("player_#{@player.id}_moves") %>
  <%= render partial: "games/moves", locals: { move_steps: nil, moves_from_hidden_boards: nil, player: @player } %>

  <%= render partial: "games/board_header", locals: { player: @player } %>

  <%= turbo_stream_from("player_#{@player.id}_game_board") %>
  <%= render partial: "games/board_grid", locals: { player: @player } %>
</div>